[project]
name = "ml-workflow"
version = "0.1.0"
description = "Machine learning example"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "scikit-learn",
    "pandas",
    "matplotlib",
    "pyarrow",
    "union",
]
